baseURL = "//marc.guyer.me"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Marc Guyer"
theme = ["hugo-cloak-email", "beautifulhugo"]
enableGitInfo = true
# pygmentsStyle = "trac"
# pygmentsUseClasses = true
pygmentsCodeFences = true
# pygmentsCodefencesGuessSyntax = true

# hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
# disableKinds = ["RSS"]
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/
googleAnalytics = "UA-69610431-1"

[author]
    name = "Marc Guyer"
    # website = "marc.guyer.me"
    email = "/contact"
    # facebook = "marcguyer"
    github = "marcguyer"
    gitlab = "marcguyer"
    # bitbucket = "username"
    # twitter = "username"
    # reddit = "username"
    linkedin = "marcguyer"
    #xing = "username"
    stackoverflow = "users/1774759/marcguyer"
    #snapchat = "username"
    instagram = "marcguyer"
    # youtube = "user/username" # or channel/channelname
    # soundcloud = "username"
    # spotify = "username"
    # bandcamp = "username"
    # itchio = "username"
    # vk = "username"
    # paypal = "username"
    # telegram = "username"
    # 500px = "username"
    # codepen = "username"
    # mastodon = "url"
    # kaggle = "username"
    # weibo = "username"
    slack = "zendframework"

[markup]
    [markup.goldmark]
        [markup.goldmark.extensions]
            definitionList = true
            footnote = true
            linkify = true
            strikethrough = true
            table = true
            taskList = true
            typographer = true
        [markup.goldmark.parser]
            attribute = true
            autoHeadingID = true
        [markup.goldmark.renderer]
            hardWraps = false
            unsafe = true
            xHTML = false
    [markup.highlight]
        codeFences = true
        hl_Lines = ""
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = true
        noClasses = true
        style = "monokai"
        tabWidth = 4
    [markup.tableOfContents]
        endLevel = 3
        startLevel = 2

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  series = "series"

[params]
  logo = "https://www.gravatar.com/avatar/e96773ada2643a59cf32d6e1407a7cc8?s=512"
  favicon = "https://www.gravatar.com/avatar/e96773ada2643a59cf32d6e1407a7cc8?s=512"
  dateFormat = "2006-01-02"
  dateform        = "2006-01-02"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  disqusShortname = "marcguyer"

  mainSections = ["posts"]
  readingTime = true
  socialShare = true
  # delayDisqus = true
  showRelatedPosts = true
  comments = true

  # Metadata mostly used in document's head
  # description = ""
  # images = [""]
  themeColor = "#494f5c"

  # Title for the browser tab and SEO
  homeTitle = "Marc Guyer"
  # for beatifulhugo
  subtitle = "Cloud Architect"
  # for hermit with my index override
  homeSubtitle = "Cloud Architect"
  # for hermit with my index override
  homeSubtitles = [
    "PHP, and Laminas (FKA Zend Framework) Specialist",
    "REST API and Payment Systems Expert",
    "Open Source Contributor",
    "Private Pilot"
  ]
  footerCopyright = ''
  # bgImg = ""  # Homepage background-image URL

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  gitUrl = "https://github.com/marcguyer/marcguyer.github.io/commit/"
  commit = "https://github.com/marcguyer/marcguyer.github.io/commit/"

  # Toggling this option needs to rebuild SCSS, requires Hugo extended version
  justifyContent = false  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  # Add custom css (hermit)
  customCSS = [
    "css/home.css",
    "css/avatar.css"
  ]

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "github"
    url = "https://github.com/marcguyer"

  [[params.social]]
    name = "stackoverflow"
    url = "https://stackoverflow.com/users/1774759/marcguyer"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/marcguyer"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url = "contact/"
    weight = 30
